apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-brother-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-brother-bot
  template:
    metadata:
      labels:
        app: big-brother-bot
    spec:
      containers:
        - name: big-brother-bot
          image: docker.io/keanuwatts/theclusterflux:BigBrotherBot
          imagePullPolicy: Always
          env:
            - name: SQLITE_SERVICE_URL
              value: "http://sqlite:8080"
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-token
                  key: token
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: big-brother-bot
spec:
  selector:
    app: big-brother-bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
